# Fluidkeys configuration file for 'fk' command
#
# # run_from_cron allows Fluidkeys to add itself to your crontab in order to
# # periodically run 'key maintain --automatic'
# # - run 'crontab -l' to see the lines added to crontab
# # - set to false and re-run fk to remove the lines from crontab
#
# run_from_cron = true
#
# [pgpkeys]
#   [pgpkeys."AAAA1111AAAA1111AAAA1111AAAA1111AAAA1111"]
#
#             ^^ keys are referenced by their OpenPGP fingerprint, see:
#                $ gpg --list-secret-keys
#
#     # store_password tells Fluidkeys to use the system keychain to store
#     # the password for this key and look for it before prompting.
#     store_password = true
#
#     # maintain_automatically specifies that key rotation tasks should be
#     # carried out without prompting when running 'fk key maintain automatic'
#     # store_password must also be true to maintain keys automatically.
#     maintain_automatically = true
#
#     # publish_to_api specifies that key will be uploaded to the Fluidkeys server and that others
#     # will be able to search for the key by email address
#     publish_to_api = true
#
# THIS FILE IS OVERWRITTEN BY FLUIDKEYS.
# Any comments you add will be lost.

run_from_cron = true

[pgpkeys]
  [pgpkeys.BB87E90E3A03BA98FD1E7C43BF20545FD5122D5D]
    store_password = false
    maintain_automatically = false
    publish_to_api = true