tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/autoupdate"

brew "mas"
brew "whalebrew"

Dir.glob("common/*.brewfile").each do |f|
  instance_eval(File.read(f))
end
